# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'Kaleboo' do

pod 'RestKit', '~> 0.24'

pod 'TTRangeSlider', '~> 1.0'
pod 'KNSemiModalViewController', '~> 0.3'
pod 'IQDropDownTextField', '~> 1.0'
pod 'FSImageViewer'
pod 'SDWebImage', '~> 3.7'
pod 'MBProgressHUD', '~> 0.9'

end

